name: dispatch
on:
  workflow_dispatch:
    inputs:
      logLevel:
        type: choice
        description: "Select log level"
        default: warning
        options:
        - info
        - warning
        - debug
      tags:
        description: "Provide tags"
        type: string
      environment:
        description: "Select environment"
        type: environment
        
jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    
    steps:
      - run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
          echo "Environment: $ENVIRONMENT"
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
          ENVIRONMENT: ${{ inputs.environment }}
