name: passing job values

on:
  workflow_dispatch:
  
jobs:
  pass_in_one_job:
    runs-on: ubuntu-latest
    steps:
      - name: Set color
        id: color-selector
        run: echo "COLOR=brown" >> "$GITHUB_OUTPUT"
      - name: Get color
        run: echo "The selected color is ${{ steps.color-selector.outputs.COLOR }}"
        
  producer:
    runs-on: ubuntu-latest
    outputs:
      message: ${{ steps.sentence_maker.outputs.SENTENCE }}
    steps:
      - name: Make a sentence
        id: sentence_maker
        run: |
            echo "SENTENCE='Hello Consumer'" >> "$GITHUB_OUTPUT"

  consumer:
    runs-on: ubuntu-latest
    needs: producer
    steps:
      - name: Print the message
        run: |
          echo ${{ needs.producer.outputs.message }}

  job_1:
    name: Add 3 and 7
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr 3 + 7 > job_1-result.txt

  job_2:
    name: Multiply by 9
    needs: job_1
    runs-on: windows-latest
    steps:
      - shell: bash
        run: |
          value=`cat job_1-result.txt`
          echo $(expr $value \* 9) 
